AllCops:
  Exclude:
    - 'lib/node_modules'

Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - 'config/main_routes.rb'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'config/initializers/**/*.rb'

Style/WordArray:
  Exclude:
    - 'config/routes.rb'
    - 'config/main_routes.rb'

Style/MixinUsage:
  Exclude:
    - 'config/routes.rb'
    - 'config/main_routes.rb'

Layout/AccessModifierIndentation:
  EnforcedStyle: 'outdent'

Metrics/LineLength:
  Max: 160

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    Default: ()
